# Site settings
title: David Larsson - dl222is
email: dl222is@student.lnu.se
description: > # this means to ignore newlines until "baseurl:"
  Frontpage for David Larsson's different assignments.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: Dassmoppen
github_username:  Manzey

# Build settings
markdown: kramdown
