# Site settings
title: Manzey
email: manzey@hotmail.se
description: > # this means to ignore newlines until "baseurl:"
  Collection page by David Larsson - gathering projects & applications throughout the years.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://manzey.github.io" # the base hostname & protocol for your site
twitter_username: Dassmoppen
github_username: manzey

# Build settings
markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]